### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by casalot** [CaptainCodeman/auth-ajax#2]
Would be great to get some more detailed docs. It seems there are multiple elements bundled in this package, so would be great to get a better view on what the options for each element is.

Very keen to try this element.

**Comment by CaptainCodeman** [comment]
Yes, that's something definitely lacking.

It was something I needed for my own use so I extracted it from a project to share but was focused on making it work first.

The `<auth-role>` element has some comments & examples of what it does / how to use it and the demo should help show the other pieces but I'll try and get to adding proper docs soon.

**Comment by CaptainCodeman** [comment]
Added docs / comments
