### ISSUE TITLE
Polymer 2.0 rewrite?

### ISSUE THREAD

**Issue by moderndeveloperllc** [CaptainCodeman/auth-ajax#8]
Just curious, are you planning on doing any kind of rewrite for polymer 2? Being able to use ES6 classes might help clean up a few things.

**Comment by CaptainCodeman** [comment]
Yeah, I have a few elements that are either being converted to Polymer 2 or else to pure WebComponents. I'll try and get them published as soon as I can (including this one).

**Comment by aydin-ozcan** [comment]
Hello Captain , 
Any news on updating this element to Polymer2

Thanks

**Comment by CaptainCodeman** [comment]
Using elements for non-UI / non-DOM functionality has really fallen out of favor. I now tend to use lit-element and would have data access through redux using fetch - it's a much better approach IMO.
